### ISSUE TITLE
bug found

### ISSUE THREAD

**Issue by Teipiou** [anton7r/a7JS#47]
$ a7 devserver
WARN Your configuration file seems empty, we are going to set it to the defaults.
C:\Users\tapio\OneDrive - Tampereen seudun toisen asteen koulutus\Projektityö\a7JS\cli\updater.js:31
if(ver.isNewer("4.0.0", pk.a7js.metadata.lastUsedVersion)){
                                ^

TypeError: Cannot read property 'metadata' of undefined
    at Object.<anonymous> (C:\Users\tapio\OneDrive - Tampereen seudun toisen asteen koulutus\Projektityö\a7JS\cli\updater.js:31:33)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\tapio\OneDrive - Tampereen seudun toisen asteen koulutus\Projektityö\a7JS\cli\cli.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)

**Comment by anton7r** [comment]
the same bug occured earlier.. it basicly deletes configurations if a7js runs into an error, we are trying to fix this issue so that this would not ever happen again.

**Comment by anton7r** [comment]
one of the solution is to make the package.json autoupdate happen when user types command `a7 fix`

**Comment by anton7r** [comment]
this was fixed last week! :) version 5.0.0-alpha2 should contain the fix
